### ISSUE TITLE
'exceptionMsg': 'IBASE_INTERFACE_USER_INTERFACE_AUTHORIZE_EXPIRED'

### ISSUE THREAD

**Issue by Sean-Huang65** [Shawn-Inspur/Yuan-1.0#12]
最近刚收到的API权限通过邮件，但是使用example中的代码调用API的时候会返回`{'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': 'IBASE_INTERFACE_USER_INTERFACE_AUTHORIZE_EXPIRED', 'resData': None}`
这个是为什么呢？

**Comment by Shawn-IEITSystems** [comment]
近期因系统原因导致访问异常，我们正在解决问题，抱歉！

**Comment by Shawn-IEITSystems** [comment]
近期因系统原因导致访问异常，我们正在解决问题，抱歉！

**Comment by lifengss** [comment]
> 

这个问题是否还存在？

**Comment by Sean-Huang65** [comment]
> > 
> 
> 这个问题是否还存在？

还是存在

**Comment by lifengss** [comment]
> 您在air.inspur.com的APIExp里测试一下，看是否有问题。如果在线上的API测试没问题，您私信我一下吧

**Comment by Sean-Huang65** [comment]
> > 您在air.inspur.com的APIExp里测试一下，看是否有问题。如果在线上的API测试没问题，您私信我一下吧

线上API报错了，错误码显示11

**Comment by lifengss** [comment]
您提供下用户名吧，看issue写的信息可能是授权过期了




发自我的华为手机


-------- 原始邮件 --------
发件人： huangzhenhuan ***@***.***>
日期： 2022年3月23日周三 中午12:38
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 'exceptionMsg': 'IBASE_INTERFACE_USER_INTERFACE_AUTHORIZE_EXPIRED' (Issue #12)

您在air.inspur.com的APIExp里测试一下，看是否有问题。如果在线上的API测试没问题，您私信我一下吧

线上API报错了，错误码显示11

―

**Comment by Sean-Huang65** [comment]
账号：qifanchao866
谢谢！



---Original---
From: "Feng ***@***.***&gt;
Date: Wed, Mar 23, 2022 13:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Shawn-Inspur/Yuan-1.0] 'exceptionMsg': 'IBASE_INTERFACE_USER_INTERFACE_AUTHORIZE_EXPIRED' (Issue #12)




 您提供下用户名吧，看issue写的信息可能是授权过期了 
 
 
 
 
 发自我的华为手机 
 
 
 -------- 原始邮件 -------- 
 发件人： huangzhenhuan ***@***.***&gt; 
 日期： 2022年3月23日周三 中午12:38 
 收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***&gt; 
 抄送： Feng Li ***@***.***&gt;, Comment ***@***.***&gt; 
 主 题： Re: [Shawn-Inspur/Yuan-1.0] 'exceptionMsg': 'IBASE_INTERFACE_USER_INTERFACE_AUTHORIZE_EXPIRED' (Issue #12) 
 
 您在air.inspur.com的APIExp里测试一下，看是否有问题。如果在线上的API测试没问题，您私信我一下吧 
 
 线上API报错了，错误码显示11 
 
 ―

**Comment by lifengss** [comment]
好了您试下，之前系统升级，应该是linux系统时间导致您的授权过期了，已经修改，您的试用期限到6月23日。感谢您的关注！

**Comment by Sean-Huang65** [comment]
可以使用了，非常感谢！
