### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by GitHubMaWu** [Shawn-Inspur/Yuan-1.0#17]
老师你好，air.inspur.com无法访问。

**Comment by Shawn-IEITSystems** [comment]
请尝试下：https://air.inspur.com/home
目前测试可以正常访问。

**Comment by lifengss** [comment]
您好，出于数据安全考虑，我们采用了https协议。我们已更新readme中的官网url，并添加了多轮对话的示例，欢迎尝试~感谢支持。
