### ISSUE TITLE
您好请问src目录下是否为提供的训练代码

### ISSUE THREAD

**Issue by birfly** [Shawn-Inspur/Yuan-1.0#2]
您好请问src目录下是否为提供的训练代码？可以直接使用吗

**Comment by AmFe-GH** [comment]
+1

**Comment by Shawn-IEITSystems** [comment]
是微调的代码，可以直接用来做微调，也可以用来做预训练，因为预训练的代码与微调的代码实质上是一样的。

**Comment by observerw** [comment]
src目录中的内容似乎与NVIDIA/Megatron-LM中的相同，请问Yuan模型本身用于训练的代码是否包含在其中了呢

**Comment by Shawn-IEITSystems** [comment]
PrefixLM、LM训练的相关代码，目前还没有包含进来，目前开源的代码聚焦在微调上。预训练的代码仍在梳理，会陆续更新。

**Comment by Thewillman** [comment]
请问能否提供Yuan-1.0的模型组成的介绍呢，我们查看论文的话这边并没有看到从NLP角度的Yuan模型内部组件构成上的详细介绍，ASC赛题这边复现模型的话有些困难

**Comment by Shawn-IEITSystems** [comment]
Hi @Thewillman ,
更新源 130亿模型的训练脚本，请参考：
https://github.com/Shawn-Inspur/Yuan-1.0/blob/main/src/pretrain_yuan_13B.sh

**Comment by Thewillman** [comment]
非常感谢，将根据这个脚本进行学习
