### ISSUE TITLE
请问是否会开源清洗语料的方案？

### ISSUE THREAD

**Issue by yayaQAQ** [Shawn-Inspur/Yuan-1.0#23]

**Comment by Shawn-IEITSystems** [comment]
这部分涉及的代码过于复杂，目前仅处于有限开源状态，如有兴趣，可向我们提交申请。

**Comment by yayaQAQ** [comment]
> 这部分涉及的代码过于复杂，目前仅处于有限开源状态，如有兴趣，可向我们提交申请。

我需要怎么申请呢？

**Comment by yayaQAQ** [comment]
> 这部分涉及的代码过于复杂，目前仅处于有限开源状态，如有兴趣，可向我们提交申请。

如果可以的话，我需要如何申请呢？
