### ISSUE TITLE
官网无法登录

### ISSUE THREAD

**Issue by zhangfelix** [Shawn-Inspur/Yuan-1.0#25]
https://air.inspur.com/home
注册提示“成功”，登录提示“错误”，没有具体错误信息。

**Comment by joejeanjean** [comment]
运营人员回复：已电联，可成功登陆了。欢迎关注源大模型。

**Comment by leochenliu** [comment]
https://air.inspur.com/user/login注册提示“成功”，登录提示“错误”，没有具体错误信息。

**Comment by leochenliu** [comment]
没有“”忘记密码“”，或重置密码的功能，请考虑加上该必要功能

**Comment by Shawn-IEITSystems** [comment]
> 

感谢给我们反馈了很好的建议！已纳入官网研发需求中。
