### ISSUE TITLE
ZEROSHOT,FEWSHOT测试脚本

### ISSUE THREAD

**Issue by Graduo** [Shawn-Inspur/Yuan-1.0#27]
您好，看您的论文中针对zeroshot、fewshot任务进行了评测，可以问您一下脚本怎么使用吗

**Comment by zhaoxudong01-ieisystem** [comment]
本地测试，请参考src/examples/generation_text_single.sh脚本，修改对应的输入文件即可。
api如何测试，请参考https://github.com/Shawn-Inspur/Yuan-1.0/tree/main/yuan_api中的使用说明
