### ISSUE TITLE
请求提示：IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY 应该如何定位和修复问题

### ISSUE THREAD

**Issue by Duan-JM** [Shawn-Inspur/Yuan-1.0#33]
Error Code
```python
import os
import sys
sys.path.append(os.path.abspath(os.curdir))

from yuan_api.inspurai import Yuan, set_yuan_account,Example

# 1. set account
set_yuan_account("我的账号", "我的手机号")  # 输入您申请的账号和手机号

# 2. initiate yuan api
# 注意：engine必需是["base_10B","translate","dialog"]之一，"base_10B"是基础模型，"translate"是翻译模型，"dialog"是对话模型
yuan = Yuan(engine="base_10B",
            input_prefix="",
            input_suffix="",
            output_prefix="",
            output_suffix="",
            append_output_prefix_to_query=False,
            topK=5,
            temperature=1,
            topP=0.8,
            frequencyPenalty=1.2)

# 3. add examples if in need.

print("====文章续写====")

while(1):
    print("输入Q退出")
    prompt = input("输入：")
    if prompt.lower() == "q":
        break
    response = yuan.submit_API(prompt=prompt)
    print(response+"")
```
Error Messages:
```bash
RuntimeWarning: {'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': 'IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY', 'resData': None}
```

**Comment by lifengss** [comment]
您好，可否具体说一下这个异常的复现步骤？

**Comment by hongyanaa** [comment]
您好，我也是这个报错，直接运行代码输入任意字符都是这个报错。

**Comment by hongyanaa** [comment]
prompt = "故宫的珍宝馆里有什么好玩的？"
response = yuan.submit_API(prompt=prompt,trun="”")
运行文档中的代码也出现此报错

**Comment by lifengss** [comment]
您运行的代码里，
`# 1. set account
set_yuan_account("我的账号", "我的手机号")  # 输入您申请的账号和手机号`
这里是否改成您申请的账号和对应的手机号了？

**Comment by hongyanaa** [comment]
改了自己用户名和手机号

**Comment by lifengss** [comment]
您好，这个情况一般是帐号没有申请开通API使用权限（官网注册用户需要提交API使用申请，审核通过后才可使用API），或者API使用权限过期导致的，需要您和后台小助手联系，反馈账号来帮助您排查。
源模型服务邮箱： air_service@inspur.com

**Comment by hongyanaa** [comment]
ok
&nbsp;


红颜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Feng ***@***.***&gt;; 
发送时间: 2022年12月11日(星期天) 上午10:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Shawn-Inspur/Yuan-1.0] 请求提示：IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY 应该如何定位和修复问题 (Issue #33)





 
您好，这个情况一般是帐号没有申请开通API使用权限（官网注册用户需要提交API使用申请，审核通过后才可使用API），或者API使用权限过期导致的，需要您和后台小助手联系，反馈账号来帮助您排查。
 源模型服务邮箱： ***@***.***

**Comment by whulxl** [comment]
> 您好，这个情况一般是帐号没有申请开通API使用权限（官网注册用户需要提交API使用申请，审核通过后才可使用API），或者API使用权限过期导致的，需要您和后台小助手联系，反馈账号来帮助您排查。 源模型服务邮箱： [air_service@inspur.com](mailto:air_service@inspur.com)

你好，我最近申请了源1.0的api权限，但是使用的时候有这个错误，“RuntimeWarning: {'errCode': 'IBASE_TOKEN_ERROR', 'errMessage': 'token验签失败', 'flag': False}”，想问下这是什么问题呢？

**Comment by lifengss** [comment]
您好，token验证失败可能是您的申请还未审批，请在官网APIExp查看是否通过审批。如果在官网apiexp可以正常测试使用API，请检查在代码中是否正确设置了用户名和手机号，以及服务器的时间是否正确。




发自我的手机


-------- 原始邮件 --------
发件人： lxl ***@***.***>
日期： 2023年1月5日周四 晚上9:38
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 请求提示：IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY 应该如何定位和修复问题 (Issue #33)

您好，这个情况一般是帐号没有申请开通API使用权限（官网注册用户需要提交API使用申请，审核通过后才可使用API），或者API使用权限过期导致的，需要您和后台小助手联系，反馈账号来帮助您排查。 源模型服务邮箱： ***@***.******@***.***>

你好，我最近申请了源1.0的api权限，但是使用的时候有这个错误，“RuntimeWarning: {'errCode': 'IBASE_TOKEN_ERROR', 'errMessage': 'token验签失败', 'flag': False}”，想问下这是什么问题呢？

―
