### ISSUE TITLE
官网和API 是否还在维护

### ISSUE THREAD

**Issue by xxyliuyang** [Shawn-Inspur/Yuan-1.0#34]
官网和API 是否还在维护中，这边调用会显示 “模型返回为空，请尝试修改输入”，在官网测试也没有返回，想问是什么情况呢，如果还在维护中，大约什么时间可用

**Comment by lifengss** [comment]
您好，目前官网API已经恢复，您可以再测试一下。给您带来的不便深表抱歉。
