### ISSUE TITLE
 hashlib 和json无法安装

### ISSUE THREAD

**Issue by heiheiheibj** [Shawn-Inspur/Yuan-1.0#35]
![image](https://user-images.githubusercontent.com/6910198/206861228-ee32f785-c71b-42bf-ad6e-685451d38a6d.png)

pip安装出现错误，看这意思象是只兼容2.x的版本
 hashlib在PYTHON 3.x中带了，还需要安装吗，或者如何解决呢，谢谢..

**Comment by lifengss** [comment]
hashlib在python3中自带，无需安装
