### ISSUE TITLE
请问官网api的申请入口关闭了吗？找不到申请api的入口？

### ISSUE THREAD

**Issue by gitctrlx** [Shawn-Inspur/Yuan-1.0#36]

**Comment by lifengss** [comment]
您好，官网首页的banner里有申请API的按钮
![image](https://user-images.githubusercontent.com/30364527/206882493-96745462-59ad-4bec-9774-66ed40120c73.png)

**Comment by FunnySaltyFish** [comment]
> 您好，官网首页的banner里有申请API的按钮 ![image](https://user-images.githubusercontent.com/30364527/206882493-96745462-59ad-4bec-9774-66ed40120c73.png)

您好，现在官网的banner一片空白，看不见申请的按钮
![image](https://user-images.githubusercontent.com/46063434/207290798-cb823ec1-4118-440b-ba36-e795e94a781a.png)

**Comment by 1438802682** [comment]
> 您好，官网首页的banner里有申请API的按钮 ![image](https://user-images.githubusercontent.com/30364527/206882493-96745462-59ad-4bec-9774-66ed40120c73.png)

您好，现在官网的banner一片空白，请问如何申请api呢？
![image](https://user-images.githubusercontent.com/76150709/207484000-1c3e6337-ea0b-466d-bbe9-3e4c6de333c3.png)

**Comment by lifengss** [comment]
您换个浏览器或者网络试试？我打开网页没有问题啊…




发自我的手机


-------- 原始邮件 --------
发件人： CtrlX ***@***.***>
日期： 2022年12月14日周三 上午9:40
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 请问官网api的申请入口关闭了吗？找不到申请api的入口？ (Issue #36)

您好，官网首页的banner里有申请API的按钮 [image] <https://user-images.githubusercontent.com/30364527/206882493-96745462-59ad-4bec-9774-66ed40120c73.png>

您好，现在官网的banner一片空白，请问如何申请api呢？
[image]<https://user-images.githubusercontent.com/76150709/207484000-1c3e6337-ea0b-466d-bbe9-3e4c6de333c3.png>

―

**Comment by evan-gyy** [comment]
我也遇到了这个问题，浏览器是Edge，梯子开不开都是显示空白，然后换成Chrome或者其他浏览器就可以正常打开
