### ISSUE TITLE
请问支持个人体验使用吗

### ISSUE THREAD

**Issue by t6am3** [Shawn-Inspur/Yuan-1.0#37]
请问支持个人体验使用吗

**Comment by lifengss** [comment]
您好支持，个人也可申请，审核通过后即可使用。

**Comment by xlbl** [comment]
审核时长多久

**Comment by lifengss** [comment]
您好，个人提交请尽量写清楚用途和研究内容，有助于工作人员通过审核。一般5个工作日内会有结果




发自我的手机


-------- 原始邮件 --------
发件人： xlbl ***@***.***>
日期： 2022年12月15日周四 晚上7:30
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 请问支持个人体验使用吗 (Issue #37)

审核时长多久

―

**Comment by xlbl** [comment]
学生没有单位填什么？支持个人体验使用吗？

**Comment by gaeduf** [comment]
我已经提交申请了 麻烦尽快审批好吗

**Comment by lifengss** [comment]
您好，运维老师反馈您的API审核已通过，请您再试一下




发自我的手机


-------- 原始邮件 --------
发件人： minglu7 ***@***.***>
日期： 2022年12月16日周五 上午10:06
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 请问支持个人体验使用吗 (Issue #37)

我已经提交申请了 麻烦尽快审批好吗

―

**Comment by xlbl** [comment]
我也提交申请了，麻烦尽快审批.用户名：bwxl66

**Comment by gaeduf** [comment]
收到

**Comment by lifengss** [comment]
您好，提交申请后工作人员将在5个工作日内完成审批。申请中遇到问题，可 以 发 邮 件 给 源 服 务 邮 ***@***.***，或者联系工作人员微信：zhoupika。申请表填写不清晰不完备可能导致审核不通过，审核不通过的话可以重新填写申请表，再次提交申请。




发自我的手机


-------- 原始邮件 --------
发件人： xlbl ***@***.***>
日期： 2022年12月16日周五 中午11:04
收件人： "Shawn-Inspur/Yuan-1.0" ***@***.***>
抄送： Feng Li ***@***.***>, Comment ***@***.***>
主 题： Re: [Shawn-Inspur/Yuan-1.0] 请问支持个人体验使用吗 (Issue #37)

我也提交申请了，麻烦尽快审批.用户名：bwxl66

―
