### ISSUE TITLE
ModuleNotFoundError: No module named 'inspurai'

### ISSUE THREAD

**Issue by arwooy** [Shawn-Inspur/Yuan-1.0#40]
git clone https://github.com/Shawn-Inspur/Yuan-1.0.git
安装后，运行from inspurai import Yuan, set_yuan_account,Example
提示ModuleNotFoundError: No module named 'inspurai' 错误

**Comment by lifengss** [comment]
应该是您的工作目录没有设置正确。请将工作目录的根目录cd到YUAN-1.0这个目录下。如果还报错，可用sys.path.append("`inspurai的绝对路径`")的方式添加检索路径

**Comment by liao0123456789** [comment]
我也是遇到楼主的问题，按照2楼的人回答已经解决了，需要添加到YUAN-1.0这个目录下才能用，从YUAN-1.0上打开。我还有一些其他模块没有安装好，pytz这些，安装好后就可以运行了
