### ISSUE TITLE
“用户授权接口信息为空”

### ISSUE THREAD

**Issue by Kathrine94** [Shawn-Inspur/Yuan-1.0#55]
请问调用api的时候显示“用户接口信息为空”是什么原因？
RuntimeWarning: {'flag': False, 'errCode': 'IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY', 'errMessage': '用户授权接口信息为空', 'exceptionMsg': None, 'resData': None}

**Comment by lifengss** [comment]
您好，这个应该是您的账号还未申请API使用或后台还未处理您的授权申请，请您耐心等待。如果有其他问题可邮件联系后台服务人员。

源模型服务邮箱： air_service@ieisystem.com
