### ISSUE TITLE
请问一下preprocess_data.py的--merge-file是什么文件

### ISSUE THREAD

**Issue by Thewillman** [Shawn-Inspur/Yuan-1.0#6]

**Comment by Henry-Avery** [comment]
我知道，不告诉你，嘻嘻

**Comment by Thewillman** [comment]
> 我知道，不告诉你，嘻嘻

向大佬低头

**Comment by zhaoxudong01-ieisystem** [comment]
merge-file是GPTTokenizer使用的文件。我们建议使用EncDecTokenizer，处理脚本参考preprocess_data_cn.py
https://github.com/Shawn-Inspur/Yuan-1.0/pull/8/commits/548c378bb86406ae78d210e23b4624f9805b2e8a

> 我知道，不告诉你，嘻嘻

**Comment by Shawn-IEITSystems** [comment]
@Thewillman 请问是否回答了你的问题？

> merge-file是GPTTokenizer使用的文件。我们建议使用EncDecTokenizer，处理脚本参考preprocess_data_cn.py [548c378](https://github.com/Shawn-Inspur/Yuan-1.0/commit/548c378bb86406ae78d210e23b4624f9805b2e8a)

**Comment by Thewillman** [comment]
> 

解决了哈哈哈哈哈哈我们在跑模型啦，谢谢官方
