### ISSUE TITLE
src/pretrain_yuan_13B.sh

### ISSUE THREAD

**Issue by ztysdu** [Shawn-Inspur/Yuan-1.0#9]
data_path_aug.txt请问这个文件应该怎么配置?里面是训练的数据集的名称吗?如果想在自己电脑上跑这个预训练程序(只有一张显卡),pretrain_yuan_13B.sh应该怎么设置啊?虽然我知道训练不完了但我还想挣扎一下,感激不尽

**Comment by zhaoxudong01-ieisystem** [comment]
> data_path_aug.txt请问这个文件应该怎么配置?里面是训练的数据集的名称吗?如果想在自己电脑上跑这个预训练程序(只有一张显卡),pretrain_yuan_13B.sh应该怎么设置啊?虽然我知道训练不完了但我还想挣扎一下,感激不尽

data_path_aug.txt格式如下：
0.1 /dataset/001.txt_document_context
0.1 /dataset/002.txt_document_context
0.1 /dataset/003.txt_document_context

前面的数字是数据文件采样的加权比例

目前的源的训练框架，无法在单个显卡上实现4B模型的训练，可以考虑借鉴deepspeed的Zero-offload方法

**Comment by Shawn-IEITSystems** [comment]
@joe483 请问我们是否回答了您的问题？

**Comment by ztysdu** [comment]
> @joe483 请问我们是否回答了您的问题？

是的,谢谢,我们最后训练完了:)

**Comment by Ant0082** [comment]
> 前面的数字是数据文件采样的加权比例

@Shawn-Inspur 你好，“前面的数字是数据文件采样的加权比例”，这里的文件采样加权比例是指？

**Comment by Ant0082** [comment]
> 

采样的目的是？

**Comment by zhaoxudong01-ieisystem** [comment]
通过加权系数控制不同数据集在训练过程中的占比

**Comment by Ant0082** [comment]
> 通过加权系数控制不同数据集在训练过程中的占比

多谢回复。
